title:             Christophe Foyer
email:             christophe@cfoyer.com
description:       Updates on my projects, activities, and more!
author:            Christophe Foyer
baseurl:           "/"
url:               "http://blog.cfoyer.com"

# Social Profiles
github_username:   Christophe-Foyer
linkedin_username:   christophe-foyer

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

#Google Analytics  
google_analytics: UA-116335955-3

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: cfoyer